name: cd

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::380875917731:role/github-actions-role
          aws-region: eu-central-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - run: |
          aws s3 sync glue/ s3://siwy-humboligerra2/scripts/